### PR TITLE
Update word2vec.py to remove the import utils

### PR DESCRIPTION
**Pull request by voaneves**
The files didn't exist and the functions are already implemented in word2vec.py.

As mentioned in #13 .

### CODE REVIEW

**Comment by alan-barzilay** [comment]
thanks, not sure how this creeped back into the files. I might have messed up some conflict resolution.

**Comment by alan-barzilay** [comment]
btw out of curiosity, do you speak portuguese? wasnt expecting anyone speaking in english in this repo haha

**Comment by voaneves** [comment]
Hey  @alan-barzilay,

Thanks for merging the commit! Regarding your question, yes, I speak Portuguese. I'm actually from Brazil as well. I tried to keep the commits in English for better accessibility and to align with common practices in open-source projects. However, if there's a preference for Portuguese, I can certainly change for that.

Speaking of which, I would like to thank you for the NLPortuguês course; it has been very beneficial!

**Comment by alan-barzilay** [comment]
ah, se vc fala portugues vou mudar pro portugues haha

>  I tried to keep the commits in English for better accessibility and to align with common practices in open-source projects. 

entendi! a ideia era deixar tudo no repo em ptbr ja que ele eh voltado para o publico lusofono, mas pode escrever na lingua q quiser haha


> Speaking of which, I would like to thank you for the NLPortuguês course; it has been very beneficial!

❤️ 
eu q agradeco por trazer atencao aos problemas! 
O coursera eh tao quebrado que jogou as mensagens do forum atual para um forum da versao experimental, quebrada e fechada da epoca q o curso ainda estava sendo desenvolvido. Como maior parte dos alunos estava vendo o mesmo forum ainda era possivel realizar a troca de ideias, mas os problemas com entregas nao estavam chegando para nos.

Caso ainda tenha interesse, o autograder foi consertado e vc deve poder realizar as entregas (soh precisa fazer uma mudanca rapida e boba no codigo da entrega 4 [q eu descrevo aqui](https://github.com/alan-barzilay/NLPortugues/issues/11#issuecomment-1951448973))

PS: ainda vou ver seu outro PR :)

**Pull request merged**
